### ISSUE TITLE
Readline & Windows

### ISSUE THREAD

**Issue by PhonieZ** [JoshuaZacek/Pass-Py-CL#1]
When you try to use Pass And Py CL on Windows, it tries to import the module 'readline', this module is used for Mac and Linux, as out of the box, which may exclude most Linux machines, they do not have readline support, this is problematic for Windows users, but there is an easy fix, which is to comment out the 'import readline' in the passandpy.py file, which is think is on line 11, this issue is going to be fixed in beta 2, so yeah, that is how you get pass and py to run.

**Comment by JoshuaZacek** [comment]
Fixed with Beta 2, now closing.
